# See /LICENSE for more information.
# This is free software, licensed under the GNU General Public License v2.

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app to set-up WED EDCCA USB mode HQoS
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all
PKG_VERSION:=1.1.0
PKG_RELEASE:=1

PKG_LICENSE:=GPL-2.0
PKG_MAINTAINER:=Andrea Pesaresi <andreapesaresi82@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
